# This workflow hard-tags and exports soft-tagged components
name: Export Components

on:
  push:
    branches: [main]

jobs:
  tag-and-export:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '--skip-ci')"
    env:
      BIT_TOKEN: ${{ secrets.BIT_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install Bit Version Manager
        run: npm i -g @teambit/bvm
      - name: Install latest Bit version
        run: bvm install
      - name: add bvm bin folder to path
        run: echo "$HOME/bin" >> $GITHUB_PATH
      - name: Set up bit config
        run: |
          bit config set analytics_reporting false
          bit config set anonymous_reporting false
          bit config set user.token $BIT_TOKEN
      - name: Install packages using bit
        run: bit install
      - name: Soft Tag if not
        run: |
          sudo apt-get install -y jq
          sh ./.github/soft-tag.sh 
      - name: Hard-tag pending components
        run: bit tag --persist
      - name: Export components
        run: bit export
      - name: Commit changes made to .bitmap
        run: sh ./.github/commit-bitmap.sh
      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        if: always()
        with:
          channel-id: 'C04J76273MZ'
          payload: |
            {
              "type": "home",
              "blocks": [
                {
                  "type": "text",
                  "text": {
                    "type": "plain_text",
                    "text": "GitHub Action build"
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "\n>Status\n>‚ùå *${{ job.status }}*"
                  }
                },
                {
                "type": "context",
                "elements": [
                  {
                    "type": "mrkdwn",
                    "text": "${{ github.event.pull_request.html_url}}/n`${{github.event.head_commit.url}}`"
                  }
                ]
              },
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}   
